//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanHistory
    {
        public long id { get; set; }
        public string command { get; set; }
        public Nullable<int> idCategory { get; set; }
        public string step { get; set; }
        public Nullable<int> status { get; set; }
        public string statusText { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
