//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebscrapEntities : DbContext
    {
        public WebscrapEntities()
            : base("name=WebscrapEntities")
        {
            Database.SetInitializer<WebscrapEntities>(new CreateDatabaseIfNotExists<WebscrapEntities>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductScan> ProductScans { get; set; }
        public virtual DbSet<ScanHistory> ScanHistories { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
    }
}
